name: cb
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope
  - astropy
  - astropy-iers-data
  - asttokens
  - brotli
  - brotli-bin
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cfitsio
  - chealpix
  - comm
  - contourpy
  - cycler
  - debugpy
  - decorator
  - ducc0
  - exceptiongroup
  - executing
  - fftw
  - fonttools
  - freetype
  - gsl
  - healpy
  - importlib-metadata
  - importlib-resources
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgfortran
  - libgfortran5
  - libjpeg-turbo
  - liblapack
  - libnghttp2
  - libopenblas
  - libpng
  - libsodium
  - libsqlite
  - libssh2
  - libtiff
  - libwebp-base
  - libxcb
  - libzlib
  - llvm-openmp
  - matplotlib-base
  - matplotlib-inline
  - munkres
  - namaster
  - ncurses
  - nest-asyncio
  - numpy
  - openjpeg
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pyerfa
  - pygments
  - pyparsing
  - python=3.9.18
  - python_abi
  - pyyaml
  - pyzmq
  - qhull
  - readline
  - scipy
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - unicodedata2
  - wcwidth
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      - camb==1.5.7
      - llvmlite==0.43.0
      - mpmath==1.3.0
      - numba==0.60.0
      - pysm3==3.4.0
      - python-dateutil==2.9.0.post0
      - sympy==1.13.1
      - toml==0.10.2
      - tqdm==4.66.5
