libdir : /global/cfs/cdirs/sobs/cosmic_birefringence/COBIv2
beta: 0.3
alpha_lat_err: 0.2
alpha_sat_err: 0.1
dust_model: 1
sync_model: 1
noise_sensitivity: baseline
galcut: 90
temperature: true
nside : 1024
which : TB